function Quary(){Load.call(this);TDDP.call(this);this.block=0;this.nonBlock=1;this.unChgPwd=5;this.authTag="auth";this.METHODGET="get";this.group;this.loginErrHandle={};this.loginUrlHashSetHandle={};this.pagePRHandle={};this.setLoginErrHandle=function(a){this.loginErrHandle=function(b){a(b)}};this.setUrlHashSet=function(a){this.loginUrlHashSetHandle=function(b,c){a(b,c)}};this.setPRHandle=function(a){this.pagePRHandle=a};this.securityEncode=function(a,b,c){var d="",e,f,h,m,k=187,l=187;f=a.length;
h=b.length;m=c.length;e=f>h?f:h;for(var g=0;g<e;g++)l=k=187,g>=f?l=b.charCodeAt(g):g>=h?k=a.charCodeAt(g):(k=a.charCodeAt(g),l=b.charCodeAt(g)),d+=c.charAt((k^l)%m);return d};this.rsf=function(a){var b=this.domainUrl,c=this;if(!1==this.local||this.routerAlive)b+="?code="+TDDP_READ+"&asyn=1",this.request(b,void 0,"post",this.ajaxAsyn,function(){c.result.errorno==EUNAUTH&&(c.parseAuthRlt(),a())})};this.postUnAuthHandle=function(a,b,c,d,e){var f=this;if(this.result.errorno==EUNAUTH){this.parseAuthRlt();
this.auth(this.pwd);if(this.result.errorno==ENONE)return this.request(this.orgURL(a),b,e,c,d),!0;window.setTimeout(function(){f.METHODGET==e.toLowerCase()?f.loginErrHandle():f.loginErrHandle(function(){})},0);return!1}return!0};this.read=function(a){var b=this.domainUrl+"?code="+TDDP_READ+"&asyn=0";this.initResult();if(!1==this.local||this.routerAlive)this.request(this.orgURL(b),a,"post",this.ajaxSyn),this.postUnAuthHandle(b,a,this.ajaxSyn,void 0,"post");return this.result.errorno};this.readEx=function(a){this.read(a);
return this.findBlock(a)};this.readNonBlock=function(a,b){var c=this.domainUrl,d=this;!1==this.local||this.routerAlive?(c+="?code="+TDDP_READ+"&asyn=1",this.request(this.orgURL(c),a,"post",this.ajaxAsyn,function(){!0==(d.result.errorno==EUNAUTH)?d.postUnAuthHandle(c,a,d.ajaxAsyn,b,"post"):b&&b(d.result)})):!0==this.local&&b&&b(d.result)};this.write=function(a,b){var c=this.domainUrl+"?code="+TDDP_WRITE+"&asyn="+b;this.initResult();if(!1==this.local||this.routerAlive)this.externLoading(!0),this.request(this.orgURL(c),
a,"post",this.ajaxSyn),this.externLoading(!1),this.postUnAuthHandle(c,a,this.ajaxSyn,void 0,"post");return this.result.errorno};this.writeNonBlock=function(a,b,c){var d=this.domainUrl,e=this;!1==this.local||this.routerAlive?(d+="?code="+TDDP_WRITE+"&asyn="+b,this.externLoading(!0),this.request(this.orgURL(d),a,"post",this.ajaxAsyn,function(){var b=e.result.errorno==EUNAUTH;!0==b&&e.postUnAuthHandle(d,a,e.ajaxAsyn,c,"post");e.externLoading(!1);!1==b&&c&&c(e.result)})):!0==this.local&&c&&c(e.result)};
this.instr=function(a,b){var c=this.domainUrl+"?code="+TDDP_INSTRUCT+"&asyn=0",d=this;this.initResult();if(!1==this.local||this.routerAlive)void 0!=b?(this.externLoading(!0),this.request(this.orgURL(c),a,"post",this.ajaxAsyn,function(e){var f=e.errorno==EUNAUTH;!0==f&&d.postUnAuthHandle(c,a,d.ajaxAsyn,b,"post");d.externLoading(!1);!1==f&&b(e)})):(this.externLoading(!0),this.request(this.orgURL(c),a,"post",this.ajaxSyn),this.externLoading(!1),this.postUnAuthHandle(c,a,this.ajaxSyn,void 0,"post"));
return this.result};this.reboot=function(){var a=this.domainUrl+"?code="+TDDP_REBOOT+"&asyn=1";this.initResult();if(!1==this.local||this.routerAlive)this.externLoading(!0),this.request(this.orgURL(a),"","post",this.ajaxSyn),this.externLoading(!1),this.postUnAuthHandle(a,"",this.ajaxSyn,void 0,"post");return this.result};this.reset=function(){var a=this.domainUrl+"?code="+TDDP_RESET+"&asyn=1";this.initResult();if(!1==this.local||this.routerAlive)this.externLoading(!0),this.request(this.orgURL(a),"",
"post",this.ajaxSyn),this.externLoading(!1),this.postUnAuthHandle(a,"",this.ajaxSyn,void 0,"post");return this.result};this.setResetSign=function(a){try{sessionLS.setItem(RESETSIGN,a),this.setWzd=a}catch(b){}};this.orgAuthPwd=function(a){return this.securityEncode(a,"RDpbLfCPsJZ7fiv","yLwVl0zKqws7LgKPRQ84Mdt708T1qQ3Ha7xv3H7NyU84p21BriUWBU43odz3iP4rBL3cD02KZciXTysVXiV8ngg6vL48rPJyAUw0HurW20xqxv9aYb4M9wK1Ae0wlro510qXeU07kV57fQMc8L6aLgMLwygtc0F10a0Dg70TOoouyFhdysuRMO51yY5ZlOZZLEal1h0t9YQW0Ko7oBwmCAHoic4HYbUyVeU3sfQ1xtXcPcf1aT303wAQhv66qzW")};
this.setLgPwd=function(a){try{sessionLS.setItem(LGKEYSTR,a),this.pwd=a}catch(b){}};this.changePwd=function(a,b){var c=this.domainUrl+"?code="+TDDP_CHGPWD+"&asyn=0&auth="+this.encodePara(a);this.initResult();if(!1==this.local||this.routerAlive)this.externLoading(!0),this.request(this.orgURL(c),b,"post",this.ajaxSyn),this.externLoading(!1),this.postUnAuthHandle(c,b,this.ajaxSyn,void 0,"post"),this.result.errorno==ENONE&&this.setLgPwd(b);return this.result};this.logout=function(){var a=this.domainUrl+
"?code="+TDDP_LOGOUT+"&asyn=0";this.initResult();if(!1==this.local||this.routerAlive)this.auth(this.pwd),this.request(this.orgURL(a),null,"post",this.ajaxSyn),this.setLgPwd(""),this.session="";return this.result};this.changeDefaultPwd=function(a){return this.changePwd("WaQ7xbhc9TefbwK",this.orgAuthPwd(a))};this.changeSysPwd=function(a,b){return this.changePwd(this.orgAuthPwd(a),this.orgAuthPwd(b))};this.parseAuthRlt=function(){var a;a=this.result.data;a.lastIndexOf("\r\n")==a.length-2&&(a=a.substring(0,
a.length-2));a=a.split("\r\n");EUNAUTH==this.result.errorno&&(authInfo[1]=a[0],authInfo[2]=a[1],authInfo[3]=a[2],authInfo[4]=a[3],$.group=a[4],$.pagePRHandle());return a};this.auth=function(a){var b=a,c=this.domainUrl+"?code="+TDDP_AUTH+"&asyn=0";if(void 0==a||0==b.length)return this.result.errorno=EUNAUTH,this.result;a=void 0;this.initResult();this.session=this.securityEncode(authInfo[3],b,authInfo[4]);c+="&id="+this.encodePara(this.session);if(!1==this.local||this.routerAlive)this.externLoading(!0),
this.request(c,a,"post",this.ajaxSyn),this.externLoading(!1);this.parseAuthRlt();ENONE==this.result.errorno&&this.setLgPwd(b);return this.result};this.getPeerMac=function(){var a=this.domainUrl+"?code="+TDDP_GETPEERMAC+"&asyn=0";this.initResult();if(!1==this.local||this.routerAlive)this.externLoading(!0),this.request(this.orgURL(a),"","post",this.ajaxSyn),this.postUnAuthHandle(a,"",this.ajaxSyn,void 0,"post"),this.externLoading(!1);return this.result}};
