var titledata = 
[
{searchtitle : "接口、 计算机接口、 指示灯、 接口怎么用", title : "外观介绍", result : "UG/zh-cn/content/01_hardware/hardware_task_about_view_MachD.html"}, 
{searchtitle : "开机、 关机、 计算机首次开机、 开启计算机、 强制关机", title : "开启和关闭计算机", result : "UG/zh-cn/content/01_hardware/hardware_task_power_on_off.html"}, 
{searchtitle : "键盘、 功能键、 键盘背光、 手指动作、 热键、 快捷键", title : "键盘", result : "UG/zh-cn/content/01_hardware/hardware_task_keyboard_key.html"}, 
{searchtitle : "键盘、 触摸板、 手指动作、 手势、 触摸板手势、 设置触摸板", title : "触摸板", result : "UG/zh-cn/content/01_hardware/hardware_task_keyboard_touchpad_01.html"}, 
{searchtitle : "充电、 给计算机充电、 充电注意事项、 电源适配器", title : "给计算机充电", result : "UG/zh-cn/content/01_hardware/hardware_task_charge_cable.html"}, 
{searchtitle : "联网、 连接无线网络、 WLAN、 wlan、 wifi、 如何连网", title : "第一步 连接无线网络", result : "UG/zh-cn/content/02_initial_setup/system_task_pc_use_wlan.html"}, 
{searchtitle : "windows、 Windows、 激活Windows、 系统激活、 激活系统、 查看Window激活、 Windows激活", title : "第二步 激活 Windows", result : "UG/zh-cn/content/02_initial_setup/system_task_pc_use_win10_activate.html"}, 
{searchtitle : "激活 Office、 Office、 office、 Office 家庭和学生版、 Office 如何激活", title : "第三步 激活 Office", result : "UG/zh-cn/content/02_initial_setup/system_task_pc_use_office_activate_huawei.html"}, 
{searchtitle : "设置指纹、 录入指纹、 指纹解锁、 指纹", title : "第四步 录入指纹", result : "UG/zh-cn/content/02_initial_setup/system_task_pc_use_fingerprint.html"}, 
{searchtitle : "驱动、 bios、 升级驱动、 驱动升级、 BIOS升级、 电脑管家", title : "第五步 升级驱动", result : "UG/zh-cn/content/02_initial_setup/system_task_pc_use_upgrade_driver.html"}, 
{searchtitle : "华为分享、 Huawei Share、 多屏协同、 无线传输、 数据同步、 文件分享", title : "华为分享", result : "UG/zh-cn/content/03_feature/feature_task_huawei_share.html"}, 
{searchtitle : "三指截屏、 三指下滑、 截图、 自由截图", title : "三指截屏（部分触摸屏计算机支持）", result : "UG/zh-cn/content/03_feature/feature_task_finger_screenshot.html"}, 
{searchtitle : "护眼模式、 护眼、 计算机护眼模式、 开启护眼模式", title : "护眼模式", result : "UG/zh-cn/content/03_feature/feature_task_eye_protection_mode.html"}, 
{searchtitle : "F10、 f10、 一键恢复出厂、 F10 一键恢复出厂、 系统还原", title : "F10 一键恢复出厂", result : "UG/zh-cn/content/03_feature/feature_task_recovery.html"}, 
{searchtitle : "开始、 开始菜单、 关机、 开始屏幕", title : "开始菜单", result : "UG/zh-cn/content/04_system/system_task_win10_start.html"}, 
{searchtitle : "操作中心、 打开操作中心、 Win10", title : "操作中心", result : "UG/zh-cn/content/04_system/system_task_win10_center.html"}, 
{searchtitle : "Docking station、 Multiport adapter、 Adapter hub、 MateDock、 External projector、 External display、 Connect to printer、 External device", title : "扩展坞（可选配件）", result : "UG/zh-cn/content/05_accessory/dock/dock_task_dock_view_01.html"}, 
{searchtitle : "连接外设、 连接电视、 连投影仪、 连接显示器、 VGA、 HDMI、 MateDock、 扩展坞", title : "连接到电视、显示器或投影仪", result : "UG/zh-cn/content/05_accessory/dock/dock_task_monitor.html"}, 
{searchtitle : "扩展坞、 了解扩展坞、 扩展坞外观、 MateDock", title : "连接 USB 鼠标、打印机或其他设备", result : "UG/zh-cn/content/05_accessory/dock/dock_task_dock_USB.html"}, 
{searchtitle : "蓝牙鼠标、 蓝牙鼠标配对、 蓝牙鼠标连接", title : "蓝牙鼠标（可选配件）", result : "UG/zh-cn/content/05_accessory/bluetoothmouse/mouse_task_bluetoothmouse_huawei.html"}, 
{searchtitle : "FAQ、 常见问题、 电源键不灵敏、 蓝屏、 黑屏、 发热、 无法连接网络、 无法连接蓝牙设备", title : "常见问题", result : "UG/zh-cn/content/06_faq/faq_topic_pc.html"}, 
{searchtitle : "用户手册说明、 手册说明、 使用说明", title : "关于本手册", result : "UG/zh-cn/content/00_common/welcome.html"}, 
{searchtitle : "安全信息、 听力保护、 环境保护", title : "安全信息", result : "UG/zh-cn/content/00_common/huawei2020/topic_level_1_cbb_pc/instance_si_pc_simplified.html"}, 
{searchtitle : "个人信息和数据安全、 个人信息、 数据安全", title : "个人信息和数据安全", result : "UG/zh-cn/content/00_common/huawei2020/topic_level_1_cbb_pc/personal_security_phone.html"}, 
{searchtitle : "法律声明、 商标声明、 隐私保护", title : "法律声明", result : "UG/zh-cn/content/00_common/huawei2020/topic_level_1_cbb_pc/instance_legal_notice_pc_simplified_01.html"}];